version: 2
updates:
  - package-ecosystem: docker
    directory: /alpine-postgres-amd64/
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /alpine-postgres-armhf/
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /alpine-postgres-aarch64/
    schedule:
      interval: weekly